# Generated by Django 4.1 on 2023-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="required_amount_to_use_coupon",
            field=models.PositiveBigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
