# Generated by Django 4.1 on 2023-10-04 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0002_coupon_required_amount_to_use_coupon"),
        ("product", "0002_product_in_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=256)),
                ("last_name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=256)),
                ("city", models.CharField(max_length=256)),
                ("zip_code", models.CharField(max_length=128)),
                ("address", models.TextField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=8)),
                ("paid", models.BooleanField(default=True)),
                ("transaction_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Received", "Received"),
                            ("On the way", "On the way"),
                            ("Delivered", "Delivered"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cart.coupon",
                    ),
                ),
                ("order_items", models.ManyToManyField(to="order.orderitem")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
    ]
